require('dotenv').config();

const CONFIG = {
  REQUEST: {
    MIN_INTERVAL: 7000,      // Minimum interval per key is 7 seconds
    MAX_BATCH_SIZE: 50,      // Size of wiki request batch
    FILE_SIZE_LIMIT: '50mb'
  },
  API: {
    KEYS: process.env.GEMINI_API_KEYS
      ? process.env.GEMINI_API_KEYS.split(',')
      : [],
    GEMINI_URL:
      "https://generativelanguage.googleapis.com/v1beta/models/" +
      "gemini-3-flash-preview:streamGenerateContent",
    GEMINI_OLD_URL:
      "https://generativelanguage.googleapis.com/v1beta/models/" +
      "gemini-2.5-flash:streamGenerateContent",
    WIKI_URL: "https://en.wikipedia.org/w/api.php"
  },
  CORS: {
    ALLOWED_ORIGINS: ["https://ko.wikipedia.org", "https://ko.m.wikipedia.org"]
  },
  TEMPLATES_TO_REMOVE: [
    '+r',
    '0r',
    '2l',
    '2long',
    'About',
    'Add references',
    'Additional citations for verification',
    'Additional citations',
    'Additionalcitations',
    'Addref',
    'Adref',
    'Advert',
    'All Plot',
    'Alternateuses',
    'Anchor',
    'And Then What',
    'Bad lead',
    'Bad-lead',
    'Bigpage',
    'Breaking News ',
    'Brief Description',
    'Build Lead',
    'Buzzword',
    'Cb',
    'Cbignore',
    'Circular Reference',
    'Citation Needed',
    'Citation style',
    'Citations Broken From Peis Limit',
    'Citations missing',
    'Citations needed',
    'Citations',
    'Citationsneeded',
    'Cite sources',
    'Citesources',
    'Clarification Needed',
    'Clarify Span',
    'Clarify',
    'Clean Bandit',
    'Clean start',
    'Clean-up categories progress',
    'Clean-up type category',
    'Cleaning tools',
    'Cleanup ',
    'Cleanup AfD',
    'Cleanup Button',
    'Cleanup Congress bio',
    'Cleanup External',
    'Cleanup HTML',
    'Cleanup ICHD',
    'Cleanup MOS',
    'Cleanup TLS',
    'Cleanup TemplateData',
    'Cleanup bare URLs',
    'Cleanup biography',
    'Cleanup book',
    'Cleanup categories',
    'Cleanup category',
    'Cleanup cite',
    'Cleanup colors',
    'Cleanup disambig',
    'Cleanup film',
    'Cleanup gallery anatomy',
    'Cleanup gallery',
    'Cleanup higher education',
    'Cleanup image accessibility',
    'Cleanup image captions',
    'Cleanup image',
    'Cleanup images',
    'Cleanup infobox',
    'Cleanup inline',
    'Cleanup lang',
    'Cleanup lead',
    'Cleanup list sort',
    'Cleanup list',
    'Cleanup merge',
    'Cleanup partial cites',
    'Cleanup press release section',
    'Cleanup press release',
    'Cleanup red links',
    'Cleanup reorganize',
    'Cleanup rewrite',
    'Cleanup road junction list',
    'Cleanup school',
    'Cleanup section',
    'Cleanup see also',
    'Cleanup split',
    'Cleanup taxobox',
    'Cleanup taxon',
    'Cleanup tense',
    'Cleanup translation section',
    'Cleanup translation',
    'Cleanup weighted',
    'Cleanup',
    'Cleanup-Section',
    'Cleanup-advert',
    'Cleanup-cat',
    'Cleanup-cite',
    'Cleanup-clarity',
    'Cleanup-context',
    'Cleanup-examples',
    'Cleanup-expert',
    'Cleanup-fiction',
    'Cleanup-laundryrack',
    'Cleanup-lead',
    'Cleanup-local',
    'Cleanup-references',
    'Cleanup-resume',
    'Cleanup-significance',
    'Cleanup-spam',
    'Cleanup-technical',
    'Cleanup-tone',
    'Cleanup-trivia',
    'Cleanup-verify',
    'CleanupBuzzwords',
    'CleanupMerge',
    'Cleanupsections',
    'Cn',
    'Coi',
    'Complex',
    'Complicated',
    'Condensed',
    'Confusing',
    'Context',
    'Copy Edit',
    'Crude TemplateData',
    'Cs1 Config',
    'Current',
    'Dead Link',
    'Default Sort',
    'Defaultsort',
    'Definition',
    'Description',
    'Disambiguation Needed',
    'Disambiguation cleanup',
    'Display Title',
    'Displaytitle',
    'Disputed',
    'Distinguish',
    'Dubious',
    'Duplication',
    'Dynamic List',
    'Engvarb',
    'Essay-Like',
    'Example Needed',
    'Excessive examples',
    'Expand Section',
    'Expand lead',
    'Expandlead',
    'Expandlede',
    'Expert needed',
    'Explain',
    'External links',
    'Fa Topicon',
    'Fact',
    'Failed Verification',
    'Fanpov',
    'Featured Article',
    'Featured List',
    'Featured',
    'Featuredarticle',
    'Few references',
    'Few refs',
    'Few sources',
    'Fewreferences',
    'Fewrefs',
    'Fiction',
    'Flux',
    'For Multi',
    'For Other Uses',
    'For The',
    'For',
    'For-Multi',
    'For1',
    'For2',
    'Forthe',
    'Full Citations Needed',
    'Fv',
    'Ga Article',
    'Ga Icon',
    'Gibberish',
    'Global',
    'Globalise',
    'Globalize',
    'Good Article',
    'Hatnote',
    'How-To',
    'Importance Section',
    'Improve Categories',
    'Improve lead',
    'Improve lede',
    'Improve references',
    'Improve refs',
    'Improve sources',
    'Improve-references',
    'Improve-refs',
    'Improveref',
    'Improvereferences',
    'Improverefs',
    'In-Universe',
    'Inadequate lead section',
    'Inadequate lead',
    'Inadequate lede',
    'Inadequate-lead',
    'Inline',
    'Insufficient lead',
    'Intro Missing',
    'Intro Needed',
    'Intro length',
    'Intro too long',
    'Intro too short',
    'Intro',
    'Intro-Missing',
    'Intro-expand',
    'Intro-rewrite',
    'Intro-too long',
    'Intro-too-long',
    'Intro-toolong',
    'Intro-tooshort',
    'Introduction Missing',
    'Introduction Needed',
    'Introlength',
    'Intromissing',
    'Introrewrite',
    'Introtoolong',
    'Italic Title',
    'Italics Title',
    'Jargon',
    'L2l',
    'L2s',
    'Lead Absent',
    'Lead Long',
    'Lead Required',
    'Lead Too Short',
    'Lead improve',
    'Lead inadequate',
    'Lead rewrite',
    'Lead section inadequate',
    'Lead section',
    'Lead',
    'Lead-rewrite',
    'Lead-too-short',
    'Leadmissing',
    'Leadsection',
    'Leadtoolong',
    'Leadtooshort',
    'Lede Absent',
    'Lede Missing',
    'Lede Required',
    'Lede rewrite',
    'Lede too long',
    'Lede too short',
    'Lede',
    'List to table',
    'Live',
    'Localist',
    'Long Plot',
    'Long intro',
    'Long lead',
    'Long',
    'Longintro',
    'Longlead',
    'Longlede',
    'Ltl',
    'Maintenance category',
    'Manual',
    'Mcn',
    'Mdy',
    'Medcn',
    'Merge From',
    'Merge To',
    'Missing Information',
    'Missing Lead',
    'Missing citations',
    'Missing references',
    'Missing refs',
    'Missingintro',
    'More Citations Needed Section',
    'More Citations Needed',
    'More Footnotes Needed',
    'More Footnotes',
    'More References',
    'More citation needed',
    'More citations',
    'More cn',
    'More ref',
    'More references needed',
    'More refs',
    'More sources needed',
    'More sources',
    'More-notes',
    'Morecite',
    'Morecn',
    'Moreinline',
    'Moreref',
    'Morereferences',
    'Morerefs',
    'Moresources',
    'Multiple Issues',
    'Multipleissues',
    'NOCITE',
    'NR',
    'Needs additional citations',
    'Needs more citations',
    'Needs more references',
    'Needs more sources',
    'Needs references',
    'Needs refs',
    'Needs sources',
    'Neutral',
    'No Context',
    'No Definition',
    'No Footnotes',
    'No Intro',
    'No Lead Section',
    'No Lead',
    'No Lede',
    'No Plot',
    'No ref',
    'No reference',
    'No references',
    'No refs',
    'No sources',
    'No-Intro',
    'No-Lead',
    'Nointro',
    'Nointroduction',
    'Nol',
    'Nolead',
    'Noleadsection',
    'Nolede',
    'Noref',
    'Noreference',
    'Noreferences',
    'Norefs',
    'Nosources',
    'Not English Inline',
    'Not English',
    'Not Neutral',
    'Not To Be Confused With',
    'Not Verified In Body',
    'Not verified',
    'Notability',
    'Notverified',
    'Npov Check',
    'Npov Dispute',
    'Npov Language',
    'Npov',
    'Npov-Check',
    'Npov-Dispute',
    'Npovcheck',
    'Npovdispute',
    'On Going',
    'One Source Section',
    'One Source',
    'Ongoing',
    'Opening',
    'Orphan',
    'Other Meanings',
    'Other People',
    'Other Uses Of',
    'Other Uses',
    'Other',
    'Othermeanings',
    'Others',
    'Otheruses',
    'Othervalues',
    'Out-Of-Date',
    'Outline',
    'Overly Detailed',
    'Page Needed',
    'Peacock',
    'Plain English',
    'Plot',
    'Pn',
    'Point Of View',
    'Portal Bar',
    'Portal',
    'Pov Check',
    'Pov Dispute',
    'Pov Problem',
    'Pov',
    'Pov-Check',
    'Pov-Dispute',
    'Povcheck',
    'Povdispute',
    'Pp',
    'Pp-Blp',
    'Pp-Dispute',
    'Pp-Extended',
    'Pp-Move',
    'Pp-Move-Dispute',
    'Pp-Move-Vandalism',
    'Pp-Office',
    'Pp-Pc',
    'Pp-Protected',
    'Pp-Semi-Indef',
    'Pp-Sock',
    'Pp-Template',
    'Pp-Usertalk',
    'Pp-Vandalism',
    'Pp-book-cover',
    'Pp-main-page',
    'Pp-upload',
    'Primary Source Inline',
    'Primary Sources',
    'Procon',
    'Promotional Source',
    'Promotional',
    'Prone To Spam',
    'Pronunciation Needed',
    'Prose',
    'Protection padlock',
    'Rdr',
    'Recategorize',
    'Recent Event',
    'Recent News',
    'Recentevent',
    'Redir',
    'Redirect',
    'Redirect-Distinguish',
    'Ref improve',
    'Ref-improve',
    'Reference Improve',
    'Referenced',
    'References needed',
    'References',
    'Refim',
    'Refimprove Section',
    'Refimprove article',
    'Refimprove',
    'Refimproved',
    'Refs needed',
    'Refsneeded',
    'Resume-like',
    'Rewrite Lead',
    'Rip',
    'Sections',
    'Semiprotected',
    'Short Desc',
    'Short Description',
    'Short intro',
    'Short lead',
    'Short-Desc',
    'Shortdesc',
    'Shorten',
    'Shortintro',
    'Shortlead',
    'Simplification Needed',
    'Single Source',
    'Source',
    'Sourceless',
    'Sources needed',
    'Sources',
    'Spam-request',
    'Specialchars',
    'Speculation Section',
    'Spin',
    'Split Section',
    'Split Sections',
    'Split',
    'Spoken',
    'Stub',
    'Stub-Section',
    'Technical',
    'This Article Is About',
    'This',
    'Toc Limit',
    'Toc',
    'Toclimit',
    'Tone',
    'Too Big',
    'Too Friendly',
    'Too Long',
    'Too Many See Alsos',
    'Too Much Jargon',
    'Too Short',
    'Too Specialized',
    'Too Technical',
    'Too few citations',
    'Too many sections',
    'Too-Long',
    'Toobig',
    'Toolong',
    'Tooshort',
    'Trivia',
    'Tsl',
    'Uncited article',
    'Uncited-article',
    'Underreferenced',
    'Undersourced',
    'Unr',
    'Unref',
    'Unref'd',
    'Unrefarticle',
    'Unreferenced Section',
    'Unreferenced article',
    'Unreferenced stub',
    'Unreferenced',
    'UnreferencedArticle',
    'Unreliable Source',
    'Unreliable Source?',
    'Unreliable Sources',
    'Unrf',
    'Unsorted list',
    'Unsourced Section',
    'Unsourced',
    'Unverified',
    'Update Inline',
    'Update Section',
    'Update',
    'Uploaded from Commons',
    'Use American English',
    'Use American spelling',
    'Use Antiguan And Barbudan English',
    'Use Australian English',
    'Use British English spelling',
    'Use British English',
    'Use Canadian English',
    'Use Dmy Dates',
    'Use Ghanaian English',
    'Use Hiberno-English spelling',
    'Use Hiberno-English',
    'Use Hong Kong English',
    'Use Indian English',
    'Use Jamaican English',
    'Use Kenyan English',
    'Use Liberian English',
    'Use List-Defined References',
    'Use Malaysian English',
    'Use Mdy Dates',
    'Use New Zealand English',
    'Use Nigerian English',
    'Use Oxford Spelling',
    'Use Pakistani English',
    'Use Philippine English',
    'Use Singapore English',
    'Use South African English',
    'Use Sri Lankan English',
    'Use Trinidad And Tobago English',
    'Use Ugandan English',
    'Vagueintro',
    'Verification',
    'Verify Credibility',
    'Verify',
    'Very Few Citations',
    'Very Long',
    'Weasel',
    'When',
    'When?',
    'White Washed',
    'Wikinews',
    'Wiktionary',
    'Wiktionary-Inline',
    'Xl'
  ],
  TEMPLATES_TO_CLEANUP: [
    { "from": ["Citation"], "to": "인용" },
    { "from": ["Cite web"], "to": "웹 인용" },
    { "from": ["Cite news"], "to": "뉴스 인용" },
    { "from": ["Cite book"], "to": "서적 인용" },
    { "from": ["Cite journal"], "to": "서적 인용" },
    { "from": ["Webarchive"], "to": "웹아카이브" },
    { "from": ["Main"], "to": "본문" },
    { "from": ["See also"], "to": "참고" },
    { "from": ["Further"], "to": "추가 정보" },
    { "from": ["Langx"], "to": "llang" },
  ],
  UPDATE_INTERVAL: 3600000,  // 1 hour
  LOGS: {
    DIR: 'log',
    SERVER: 'server.log',
    API_TRANSLATE: 'api_translate.log',
    API_CREATE: 'api_create.log'
  }
};

module.exports = CONFIG;

